// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZOOxZRAXfH2IlXnFGAVd9sJcD88d1Umw',
    appId: '1:981393948779:web:0458ad5452fa37c6d4f12e',
    messagingSenderId: '981393948779',
    projectId: 'etiler-a60d1',
    authDomain: 'etiler-a60d1.firebaseapp.com',
    storageBucket: 'etiler-a60d1.firebasestorage.app',
    measurementId: 'G-TD845PFPPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiSvoxlvXcdxQnf18TYC4cC8e_0D_CxSk',
    appId: '1:981393948779:android:f2c7b86e0331169fd4f12e',
    messagingSenderId: '981393948779',
    projectId: 'etiler-a60d1',
    storageBucket: 'etiler-a60d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiHKrnC7qQXeW4WHv7Ys2N1jXOa_iGKKc',
    appId: '1:981393948779:ios:55235e908945055cd4f12e',
    messagingSenderId: '981393948779',
    projectId: 'etiler-a60d1',
    storageBucket: 'etiler-a60d1.firebasestorage.app',
    iosBundleId: 'com.example.stokApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiHKrnC7qQXeW4WHv7Ys2N1jXOa_iGKKc',
    appId: '1:981393948779:ios:55235e908945055cd4f12e',
    messagingSenderId: '981393948779',
    projectId: 'etiler-a60d1',
    storageBucket: 'etiler-a60d1.firebasestorage.app',
    iosBundleId: 'com.example.stokApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZOOxZRAXfH2IlXnFGAVd9sJcD88d1Umw',
    appId: '1:981393948779:web:e630fc38195d8298d4f12e',
    messagingSenderId: '981393948779',
    projectId: 'etiler-a60d1',
    authDomain: 'etiler-a60d1.firebaseapp.com',
    storageBucket: 'etiler-a60d1.firebasestorage.app',
    measurementId: 'G-W0SNWYTCEH',
  );
}
